# -*- coding: utf-8 -*-
"""Manipulação de estéreis — bloco 13 do roteiro de manipulação no site Medicamentos.

Fonte das perguntas: RDC 67/2007, Anexo VII (roteiro de inspeção), item 18
"Manipulação de produtos estéreis", na ordem e com a classificação oficial
(I imprescindível, N necessário, R recomendável, INF informativo). Perguntas que
no Anexo VII dependem da anterior ("Existem registros?", "Está validado?") foram
reescritas para ficarem compreensíveis sozinhas; o número do Anexo VII é mantido.
Cada pergunta cita o item correspondente do Anexo IV (Boas Práticas de
Manipulação de Produtos Estéreis), cujo texto vem do banco legislativo v12.

Formato: (nº Anexo VII, classe, pergunta, frase se cumpre, frase se não cumpre,
[itens do Anexo IV]). Nas informativas (INF), a segunda frase descreve o "Não".
"""

SECOES = [
    ('13.1', 'Condições gerais', None, ['18.1']),
    ('13.2', 'Pessoal, higiene e conduta', None, ['18.2.1', '18.2.2', '18.2.3', '18.2.4', '18.2.5']),
    ('13.3', 'Vestuário e paramentação', None, ['18.2.6', '18.2.7', '18.2.8', '18.2.9', '18.2.10', '18.2.11', '18.2.12', '18.2.13', '18.2.14', '18.2.15', '18.2.16', '18.2.17', '18.2.18']),
    ('13.4', 'Áreas, acabamento e sanitização', None, ['18.3.1', '18.3.2', '18.3.3', '18.3.4', '18.3.5', '18.3.6', '18.3.7', '18.3.8', '18.3.9', '18.3.10', '18.3.11', '18.3.12', '18.3.13', '18.3.14']),
    ('13.5', 'Salas classificadas e antecâmara', None, ['18.3.15', '18.3.16', '18.3.17', '18.3.18', '18.3.19', '18.3.20', '18.3.21', '18.3.22', '18.3.23', '18.3.24', '18.3.25']),
    ('13.6', 'Equipamentos e mobiliário', None, ['18.4']),
    ('13.7', 'Materiais', None, ['18.5']),
    ('13.8', 'Água para injetáveis', None, ['18.6']),
    ('13.9', 'Manipulação asséptica', None, ['18.7.1', '18.7.2', '18.7.3', '18.7.4', '18.7.5', '18.7.6', '18.7.7', '18.7.8', '18.7.9', '18.7.10', '18.7.11', '18.7.12']),
    ('13.10', 'Esterilização, envase e revisão', None, ['18.7.13', '18.7.14', '18.7.15', '18.7.16', '18.7.17', '18.7.18', '18.7.19', '18.7.20', '18.7.21', '18.7.22', '18.7.23', '18.7.24']),
    ('13.11', 'Controle de qualidade', None, ['18.8']),
    ('13.12', 'Garantia da qualidade e validação', None, ['18.9']),
    ('13.13', 'Citostáticos', 'citostaticos', ['18.10']),
]

P = [
 # 18.1 Condições gerais
 ('18.1.1', 'N', 'É realizado o efetivo monitoramento de todo o processo de preparação, de modo a garantir ao paciente a qualidade da preparação a ser administrada?',
  'Há monitoramento efetivo de todo o processo de preparação dos estéreis.', 'Não há monitoramento efetivo de todo o processo de preparação dos estéreis.', ['2.2']),
 ('18.1.2', 'INF', 'A farmácia manipula produtos usados em terapia antineoplásica?',
  'A farmácia manipula produtos usados em terapia antineoplásica.', 'A farmácia não manipula produtos usados em terapia antineoplásica.', ['2.4', '2.5']),
 # 18.2 Pessoal
 ('18.2.1', 'N', 'Todo o pessoal envolvido com a manipulação de estéreis conhece os princípios das Boas Práticas de Manipulação de Produtos Estéreis?',
  'O pessoal envolvido conhece os princípios das Boas Práticas de Manipulação de Produtos Estéreis.', 'Não foi comprovado que o pessoal envolvido conhece os princípios das Boas Práticas de Manipulação de Produtos Estéreis.', ['3.1']),
 ('18.2.2', 'N', 'O acesso às áreas de preparação de estéreis é restrito aos operadores diretamente envolvidos?',
  'O acesso às áreas de preparação de estéreis é restrito aos operadores envolvidos.', 'O acesso às áreas de preparação de estéreis não é restrito aos operadores envolvidos.', ['3.2.1']),
 ('18.2.3', 'I', 'Os manipuladores de produtos estéreis atendem a um alto nível de higiene?',
  'Os manipuladores de estéreis atendem a alto nível de higiene.', 'Os manipuladores de estéreis não atendem ao nível de higiene exigido.', ['3.2.2']),
 ('18.2.4', 'N', 'Os manipuladores são instruídos a lavar mãos e antebraços, com escovação das unhas e antisséptico padronizado, antes de entrar na área de manipulação?',
  'Os manipuladores são instruídos a lavar mãos e antebraços, com escovação das unhas e antisséptico padronizado, antes de entrar na área.', 'Os manipuladores não são instruídos a lavar mãos e antebraços, com escovação das unhas e antisséptico padronizado, antes de entrar na área.', ['3.2.2']),
 ('18.2.5', 'N', 'Os operadores da inspeção visual fazem exames oftalmológicos periódicos e têm intervalos de descanso frequentes?',
  'Os operadores da inspeção visual fazem exames oftalmológicos periódicos e têm intervalos de descanso.', 'Os operadores da inspeção visual não fazem exames oftalmológicos periódicos ou não têm intervalos de descanso.', ['3.2.3']),
 # 18.2 Vestuário
 ('18.2.6', 'I', 'Os funcionários da manipulação de estéreis estão uniformizados de forma a proteger a preparação contra contaminação?',
  'Os funcionários estão uniformizados de forma a proteger a preparação contra contaminação.', 'Os funcionários não estão uniformizados de forma a proteger a preparação contra contaminação.', ['3.3.1']),
 ('18.2.7', 'N', 'Os uniformes são trocados a cada sessão de manipulação?',
  'Os uniformes são trocados a cada sessão de manipulação.', 'Os uniformes não são trocados a cada sessão de manipulação.', ['3.3.1']),
 ('18.2.8', 'N', 'A colocação de uniformes e calçados e a higiene para entrar nas áreas classificadas são feitas em sala específica de paramentação?',
  'A paramentação para as áreas classificadas é feita em sala específica.', 'A paramentação para as áreas classificadas não é feita em sala específica.', ['3.3.2']),
 ('18.2.9', 'N', 'A paramentação segue procedimento estabelecido para evitar contaminação microbiana e por partículas?',
  'A paramentação segue procedimento estabelecido.', 'A paramentação não segue procedimento estabelecido.', ['3.3.2']),
 ('18.2.10', 'I', 'Os uniformes e calçados das áreas classificadas cobrem completamente o corpo?',
  'Os uniformes e calçados das áreas classificadas cobrem completamente o corpo.', 'Os uniformes e calçados das áreas classificadas não cobrem completamente o corpo.', ['3.3.3']),
 ('18.2.11', 'N', 'O tecido dos uniformes das áreas classificadas não libera partículas ou fibras?',
  'O tecido dos uniformes das áreas classificadas não libera partículas ou fibras.', 'O tecido dos uniformes das áreas classificadas libera partículas ou fibras.', ['3.3.4']),
 ('18.2.12', 'I', 'Os uniformes da sala de manipulação, inclusive máscaras e luvas, são estéreis?',
  'Os uniformes da sala de manipulação, inclusive máscaras e luvas, são estéreis.', 'Os uniformes da sala de manipulação, máscaras ou luvas não são estéreis.', ['3.3.5']),
 ('18.2.13', 'I', 'Os uniformes da sala de manipulação são substituídos a cada sessão de manipulação?',
  'Os uniformes da sala de manipulação são substituídos a cada sessão.', 'Os uniformes da sala de manipulação não são substituídos a cada sessão.', ['3.3.5']),
 ('18.2.14', 'N', 'As luvas estéreis são trocadas a cada 2 horas de manipulação e sempre que sua integridade estiver comprometida?',
  'As luvas estéreis são trocadas a cada 2 horas e sempre que comprometidas.', 'As luvas estéreis não são trocadas a cada 2 horas ou quando comprometidas.', ['3.3.6']),
 ('18.2.15', 'N', 'Os uniformes reutilizáveis ficam separados, em ambiente fechado, até serem lavados e esterilizados?',
  'Os uniformes reutilizáveis ficam separados, em ambiente fechado, até a lavagem e esterilização.', 'Os uniformes reutilizáveis não ficam separados em ambiente fechado até a lavagem e esterilização.', ['3.3.7']),
 ('18.2.16', 'I', 'A lavagem e a esterilização dos uniformes são feitas sob responsabilidade da empresa?',
  'A lavagem e a esterilização dos uniformes são feitas sob responsabilidade da empresa.', 'A lavagem e a esterilização dos uniformes não estão sob responsabilidade da empresa.', ['3.3.7']),
 ('18.2.17', 'INF', 'A lavagem e a esterilização dos uniformes são feitas por empresa terceirizada?',
  'A lavagem e a esterilização dos uniformes são terceirizadas.', 'A lavagem e a esterilização dos uniformes são feitas pela própria farmácia.', ['3.3.7.1']),
 ('18.2.17.1', 'R', 'Quando terceirizadas, há contrato formal para a lavagem e esterilização dos uniformes?',
  'Há contrato formal para a lavagem e esterilização terceirizada dos uniformes.', 'Recomenda-se formalizar em contrato a lavagem e esterilização terceirizada dos uniformes.', ['3.3.7.1']),
 ('18.2.18', 'N', 'A lavagem e a esterilização dos uniformes seguem procedimentos escritos?',
  'A lavagem e a esterilização dos uniformes seguem procedimentos escritos.', 'A lavagem e a esterilização dos uniformes não seguem procedimentos escritos.', ['3.3.8']),
 ('18.2.18.1', 'N', 'O processo de lavagem e esterilização dos uniformes está validado?',
  'O processo de lavagem e esterilização dos uniformes está validado.', 'O processo de lavagem e esterilização dos uniformes não está validado.', ['3.3.8']),
 # 18.3 Infraestrutura
 ('18.3.1', 'N', 'A área de preparação de estéreis foi projetada e construída ou adaptada segundo padrões técnicos, com infraestrutura adequada às operações?',
  'A área de preparação de estéreis tem infraestrutura adequada às operações.', 'A área de preparação de estéreis não tem infraestrutura adequada às operações.', ['4.1']),
 ('18.3.2', 'N', 'Além das áreas comuns, há sala de limpeza, higienização e esterilização; sala ou local de pesagem; sala exclusiva de manipulação e envase; área de revisão; área de quarentena, rotulagem e embalagem; e antecâmara de paramentação?',
  'A farmácia dispõe das salas e áreas exigidas para estéreis.', 'A farmácia não dispõe de todas as salas e áreas exigidas para estéreis.', ['4.2', '4.3']),
 ('18.3.3', 'N', 'Nas salas de pesagem, manipulação e envase, as superfícies são revestidas de material resistente aos sanitizantes?',
  'As superfícies das salas de pesagem, manipulação e envase resistem aos sanitizantes.', 'As superfícies das salas de pesagem, manipulação e envase não resistem aos sanitizantes.', ['4.4']),
 ('18.3.4', 'N', 'As superfícies são lisas e impermeáveis, com cantos arredondados?',
  'As superfícies são lisas e impermeáveis, com cantos arredondados.', 'As superfícies não são lisas e impermeáveis ou não têm cantos arredondados.', ['4.4']),
 ('18.3.5', 'N', 'As salas de pesagem, manipulação e envase evitam superfícies de difícil limpeza?',
  'As salas de pesagem, manipulação e envase não têm superfícies de difícil limpeza.', 'As salas de pesagem, manipulação e envase têm superfícies de difícil limpeza.', ['4.5']),
 ('18.3.6', 'N', 'Não há portas corrediças nessas salas?',
  'Não há portas corrediças nas salas de pesagem, manipulação e envase.', 'Há portas corrediças nas salas de pesagem, manipulação e envase.', ['4.5']),
 ('18.3.7', 'N', 'Os tetos rebaixados, quando existem, são completamente vedados?',
  'Os tetos rebaixados são completamente vedados.', 'Os tetos rebaixados não são completamente vedados.', ['4.6']),
 ('18.3.8', 'N', 'As tubulações das salas de pesagem, manipulação e envase são embutidas na parede?',
  'As tubulações das salas de pesagem, manipulação e envase são embutidas.', 'Há tubulações aparentes nas salas de pesagem, manipulação e envase.', ['4.7']),
 ('18.3.9', 'N', 'É feito o controle da contaminação ambiental do ar e das superfícies, com parâmetros estabelecidos e procedimento escrito?',
  'É feito o controle da contaminação do ar e das superfícies, com parâmetros e procedimento escrito.', 'Não é feito o controle da contaminação do ar e das superfícies com parâmetros e procedimento escrito.', ['4.8']),
 ('18.3.10', 'N', 'Há registros dos resultados do controle da contaminação do ar e das superfícies?',
  'Há registros do controle da contaminação do ar e das superfícies.', 'Não há registros do controle da contaminação do ar e das superfícies.', ['4.8']),
 ('18.3.11', 'N', 'Nas áreas classificadas é usado mais de um tipo de desinfetante, com alternância periódica?',
  'Há alternância periódica de desinfetantes nas áreas classificadas.', 'Não há alternância periódica de desinfetantes nas áreas classificadas.', ['4.9']),
 ('18.3.12', 'N', 'A sanitização é monitorada periodicamente para detectar microrganismos persistentes ou resistentes?',
  'A sanitização é monitorada periodicamente quanto a microrganismos persistentes ou resistentes.', 'A sanitização não é monitorada quanto a microrganismos persistentes ou resistentes.', ['4.10']),
 ('18.3.13', 'I', 'Não há pia nem ralo, mesmo sifonados, nas salas de pesagem e de manipulação e envase?',
  'Não há pia nem ralo nas salas de pesagem e de manipulação e envase.', 'Há pia ou ralo nas salas de pesagem ou de manipulação e envase.', ['4.11']),
 ('18.3.14', 'N', 'O acesso às salas de limpeza e esterilização, pesagem e manipulação e envase é feito por antecâmara?',
  'O acesso às salas de limpeza e esterilização, pesagem e manipulação é feito por antecâmara.', 'O acesso às salas de limpeza e esterilização, pesagem ou manipulação não é feito por antecâmara.', ['4.12']),
 ('18.3.15', 'N', 'A sala de lavagem, esterilização e despirogenização dos recipientes vazios é separada das demais?',
  'A sala de lavagem, esterilização e despirogenização de recipientes é separada.', 'A sala de lavagem, esterilização e despirogenização de recipientes não é separada.', ['4.13.1']),
 ('18.3.15.1', 'N', 'Essa sala tem classificação ISO 8?',
  'A sala de lavagem e esterilização de recipientes tem classificação ISO 8.', 'A sala de lavagem e esterilização de recipientes não tem classificação ISO 8 comprovada.', ['4.13.1']),
 ('18.3.16', 'N', 'A limpeza e a higienização de medicamentos e produtos para saúde usados na manipulação de estéreis também são feitas em área ISO 8?',
  'A limpeza de medicamentos e produtos para saúde usados na manipulação é feita em área ISO 8.', 'A limpeza de medicamentos e produtos para saúde usados na manipulação não é feita em área ISO 8.', ['4.13.2']),
 ('18.3.17', 'N', 'A sala de limpeza é contígua à de manipulação, com passagem de dupla porta para entrada de material?',
  'A sala de limpeza é contígua à de manipulação, com passagem de dupla porta.', 'A sala de limpeza não é contígua à de manipulação ou não tem passagem de dupla porta.', ['4.13.3']),
 ('18.3.18', 'N', 'Há meios e equipamentos para limpar e esterilizar os materiais antes da entrada na sala de manipulação?',
  'Há meios para limpar e esterilizar os materiais antes da entrada na sala de manipulação.', 'Não há meios para limpar e esterilizar os materiais antes da entrada na sala de manipulação.', ['4.13.4']),
 ('18.3.19', 'N', 'A sala de pesagem tem classificação ISO 7?',
  'A sala de pesagem tem classificação ISO 7.', 'A sala de pesagem não tem classificação ISO 7 comprovada.', ['4.14.1']),
 ('18.3.20', 'I', 'A sala de manipulação e envase de estéreis é independente e exclusiva?',
  'A sala de manipulação e envase de estéreis é independente e exclusiva.', 'A sala de manipulação e envase de estéreis não é independente e exclusiva.', ['4.15.1']),
 ('18.3.20.1', 'I', 'A manipulação ocorre em ambiente ISO 5 (sala ISO 5 ou fluxo laminar ISO 5 em área ISO 7), com filtros de ar?',
  'A manipulação ocorre em ambiente ISO 5, com filtração do ar.', 'A manipulação não ocorre em ambiente ISO 5 comprovado.', ['4.15.1']),
 ('18.3.20.2', 'N', 'A sala de manipulação tem pressão positiva em relação às salas adjacentes?',
  'A sala de manipulação tem pressão positiva em relação às adjacentes.', 'A sala de manipulação não tem pressão positiva em relação às adjacentes.', ['4.15.1']),
 ('18.3.21', 'N', 'Há área específica de revisão, com iluminação e contraste adequados à inspeção dos produtos envasados?',
  'Há área de revisão com iluminação e contraste adequados.', 'Não há área de revisão com iluminação e contraste adequados.', ['4.16.1']),
 ('18.3.22', 'N', 'A área de quarentena, rotulagem e embalagem é suficiente para operações racionais e ordenadas?',
  'A área de quarentena, rotulagem e embalagem é suficiente.', 'A área de quarentena, rotulagem e embalagem é insuficiente.', ['4.17.1']),
 ('18.3.23', 'R', 'A antecâmara tem câmaras fechadas, com barreira sujo/limpo para troca de roupa?',
  'A antecâmara tem barreira sujo/limpo para troca de roupa.', 'Recomenda-se dotar a antecâmara de barreira sujo/limpo para troca de roupa.', ['4.18.1']),
 ('18.3.24', 'R', 'As portas da antecâmara e das salas classificadas impedem a abertura simultânea?',
  'As portas da antecâmara e das salas classificadas impedem a abertura simultânea.', 'Recomenda-se instalar dispositivo que impeça a abertura simultânea das portas da antecâmara e das salas classificadas.', ['4.18.2']),
 ('18.3.25', 'N', 'A antecâmara é ventilada com ar filtrado?',
  'A antecâmara é ventilada com ar filtrado.', 'A antecâmara não é ventilada com ar filtrado.', ['4.18.3']),
 ('18.3.25.1', 'N', 'A pressão da antecâmara é inferior à da sala de manipulação e superior à da área externa?',
  'A pressão da antecâmara é intermediária entre a sala de manipulação e a área externa.', 'A pressão da antecâmara não é intermediária entre a sala de manipulação e a área externa.', ['4.18.3']),
 ('18.3.25.2', 'R', 'O lavatório tem torneira ou comando sem contato das mãos?',
  'O lavatório tem comando sem contato das mãos.', 'Recomenda-se dotar o lavatório de comando sem contato das mãos.', ['4.18.4']),
 ('18.3.25.3', 'N', 'Junto ao lavatório há sabonete líquido ou antisséptico e recurso para secagem das mãos?',
  'Há sabonete líquido ou antisséptico e recurso para secagem das mãos junto ao lavatório.', 'Não há sabonete líquido ou antisséptico e recurso para secagem das mãos junto ao lavatório.', ['4.18.4']),
 # 18.4 Equipamentos
 ('18.4.1', 'N', 'Os equipamentos estão localizados, instalados e mantidos de forma adequada às operações?',
  'Os equipamentos estão instalados e mantidos de forma adequada às operações.', 'Os equipamentos não estão instalados ou mantidos de forma adequada às operações.', ['5.1']),
 ('18.4.2', 'N', 'A estrutura dos equipamentos permite limpá-los efetivamente e mantê-los limpos?',
  'A estrutura dos equipamentos permite a limpeza efetiva.', 'A estrutura dos equipamentos não permite a limpeza efetiva.', ['5.2']),
 ('18.4.3', 'N', 'Os equipamentos da manipulação de estéreis podem ser esterilizados por vapor, calor seco ou outro método?',
  'Os equipamentos da manipulação de estéreis podem ser esterilizados.', 'Há equipamentos da manipulação de estéreis que não podem ser esterilizados.', ['5.3']),
 ('18.4.4', 'N', 'Os desinfetantes e detergentes são monitorados quanto à contaminação microbiana?',
  'Os desinfetantes e detergentes são monitorados quanto à contaminação microbiana.', 'Os desinfetantes e detergentes não são monitorados quanto à contaminação microbiana.', ['5.6']),
 ('18.4.5', 'N', 'Ao final da manipulação, os equipamentos são limpos, desinfetados e identificados quanto à condição?',
  'Ao final da manipulação, os equipamentos são limpos, desinfetados e identificados.', 'Ao final da manipulação, os equipamentos não são limpos, desinfetados e identificados.', ['5.7']),
 ('18.4.5.1', 'N', 'Há registros da limpeza e desinfecção dos equipamentos ao final da manipulação?',
  'Há registros da limpeza e desinfecção dos equipamentos.', 'Não há registros da limpeza e desinfecção dos equipamentos.', ['5.7']),
 ('18.4.6', 'I', 'O ar injetado nas áreas classificadas é filtrado por filtros HEPA?',
  'O ar das áreas classificadas é filtrado por filtros HEPA.', 'O ar das áreas classificadas não é filtrado por filtros HEPA.', ['5.10']),
 ('18.4.7', 'N', 'Os equipamentos têm manutenção preventiva em programa formal e corretiva quando necessário?',
  'Os equipamentos têm manutenção preventiva em programa formal e corretiva quando necessário.', 'Os equipamentos não têm programa formal de manutenção preventiva.', ['5.12']),
 ('18.4.8', 'N', 'Há procedimentos escritos para a manutenção dos equipamentos?',
  'Há procedimentos escritos para a manutenção dos equipamentos.', 'Não há procedimentos escritos para a manutenção dos equipamentos.', ['5.12']),
 ('18.4.9', 'N', 'Há registros das manutenções preventivas e corretivas?',
  'Há registros das manutenções preventivas e corretivas.', 'Não há registros das manutenções preventivas e corretivas.', ['5.12.1']),
 ('18.4.10', 'I', 'O equipamento de tratamento de água produz água com especificação de água para injetáveis?',
  'O equipamento de tratamento produz água com especificação de água para injetáveis.', 'O equipamento de tratamento não produz água com especificação de água para injetáveis.', ['5.13', '7.2.1']),
 ('18.4.11', 'N', 'O sistema de produção de água é sanitizado conforme procedimento escrito?',
  'O sistema de produção de água é sanitizado conforme procedimento escrito.', 'O sistema de produção de água não é sanitizado conforme procedimento escrito.', ['5.14']),
 ('18.4.11.1', 'N', 'Há registros da sanitização do sistema de produção de água?',
  'Há registros da sanitização do sistema de produção de água.', 'Não há registros da sanitização do sistema de produção de água.', ['5.14']),
 ('18.4.12', 'N', 'O sistema de distribuição da água garante que não haja contaminação microbiana?',
  'O sistema de distribuição da água impede a contaminação microbiana.', 'O sistema de distribuição da água não impede a contaminação microbiana.', ['5.15']),
 ('18.4.13', 'N', 'Se a água é armazenada, usam-se recipientes de aço inoxidável, herméticos e com filtro de ar esterilizante?',
  'A água é armazenada em recipientes de aço inoxidável, herméticos e com filtro de ar esterilizante.', 'A água é armazenada em recipientes fora do padrão exigido.', ['5.16']),
 ('18.4.14', 'N', 'O mobiliário é liso, impermeável, facilmente lavável e não libera partículas?',
  'O mobiliário é liso, impermeável, lavável e não libera partículas.', 'O mobiliário não é liso, impermeável ou lavável, ou libera partículas.', ['5.17']),
 ('18.4.14.1', 'N', 'O mobiliário suporta a desinfecção pelos agentes normalmente usados?',
  'O mobiliário suporta a desinfecção pelos agentes utilizados.', 'O mobiliário não suporta a desinfecção pelos agentes utilizados.', ['5.17']),
 # 18.5 Materiais
 ('18.5.1', 'N', 'As matérias-primas adquiridas são analisadas quanto a todas as especificações dos compêndios oficiais, incluindo a biocarga?',
  'As matérias-primas são analisadas conforme os compêndios oficiais, incluindo a biocarga.', 'As matérias-primas não são analisadas conforme os compêndios oficiais, incluindo a biocarga.', ['6.1.1']),
 ('18.5.2', 'N', 'As especialidades farmacêuticas e os produtos para saúde usados no preparo seguem especificação técnica do farmacêutico e estão regularizados na Anvisa?',
  'As especialidades farmacêuticas e os produtos para saúde seguem especificação técnica e estão regularizados na Anvisa.', 'Há especialidades farmacêuticas ou produtos para saúde sem especificação técnica ou sem regularização na Anvisa.', ['6.1.2']),
 ('18.5.3', 'N', 'Cada lote é acompanhado do certificado de análise do fabricante?',
  'Cada lote é acompanhado do certificado de análise do fabricante.', 'Há lotes sem certificado de análise do fabricante.', ['6.1.3']),
 # 18.6 Água
 ('18.6.1', 'N', 'A água de abastecimento, o sistema de tratamento e a água tratada são monitorados regularmente?',
  'A água de abastecimento, o sistema de tratamento e a água tratada são monitorados regularmente.', 'A água de abastecimento, o sistema de tratamento ou a água tratada não são monitorados regularmente.', ['7.1']),
 ('18.6.1.1', 'N', 'Há registros dos resultados desse monitoramento?',
  'Há registros do monitoramento da água.', 'Não há registros do monitoramento da água.', ['7.1']),
 ('18.6.2', 'I', 'A água usada na preparação de estéreis é obtida por destilação ou osmose reversa, com características de água para injetáveis?',
  'A água usada na preparação de estéreis tem características de água para injetáveis.', 'A água usada na preparação de estéreis não tem características comprovadas de água para injetáveis.', ['7.2.1', '7.2.2']),
 ('18.6.2.1', 'INF', 'A água para injetáveis é obtida no próprio estabelecimento?',
  'A água para injetáveis é obtida no próprio estabelecimento.', 'A água para injetáveis é adquirida de indústria farmacêutica.', ['7.2.1', '7.2.2']),
 ('18.6.3', 'N', 'A água de enxágue de ampolas e recipientes de envase tem qualidade de água para injetáveis?',
  'A água de enxágue de ampolas e recipientes tem qualidade de água para injetáveis.', 'A água de enxágue de ampolas e recipientes não tem qualidade de água para injetáveis.', ['7.2.3']),
 ('18.6.4', 'INF', 'A farmácia armazena a água para injetáveis?',
  'A farmácia armazena a água para injetáveis.', 'A farmácia não armazena a água para injetáveis.', ['7.2.4']),
 ('18.6.4.1', 'N', 'Se armazenada, a água é mantida em recirculação a 80 °C ou mais?',
  'A água armazenada é mantida em recirculação a 80 °C ou mais.', 'A água armazenada não é mantida em recirculação a 80 °C ou mais.', ['7.2.4']),
 ('18.6.4.2', 'I', 'Se não há recirculação a 80 °C, a água é descartada a cada 24 horas?',
  'A água sem recirculação é descartada a cada 24 horas.', 'A água sem recirculação não é descartada a cada 24 horas.', ['7.2.4']),
 ('18.6.5', 'N', 'Há procedimentos escritos de limpeza e manutenção do sistema de obtenção de água para injetáveis?',
  'Há procedimentos escritos de limpeza e manutenção do sistema de água para injetáveis.', 'Não há procedimentos escritos de limpeza e manutenção do sistema de água para injetáveis.', ['7.2.5']),
 ('18.6.5.1', 'N', 'Há registros da limpeza e manutenção desse sistema?',
  'Há registros da limpeza e manutenção do sistema de água para injetáveis.', 'Não há registros da limpeza e manutenção do sistema de água para injetáveis.', ['7.2.5']),
 ('18.6.6', 'I', 'São feitos os testes físico-químicos e microbiológicos de água purificada e o teste de endotoxinas bacterianas?',
  'São feitos os testes físico-químicos, microbiológicos e de endotoxinas da água.', 'Não são feitos os testes físico-químicos, microbiológicos ou de endotoxinas da água.', ['7.2.6']),
 ('18.6.6.1', 'I', 'Há registros desses testes da água?',
  'Há registros dos testes da água.', 'Não há registros dos testes da água.', ['7.2.6']),
 ('18.6.7', 'I', 'A condutividade e as endotoxinas da água são verificadas imediatamente antes do uso (endotoxinas dispensadas para oftálmicos)?',
  'A condutividade e as endotoxinas da água são verificadas imediatamente antes do uso.', 'A condutividade e as endotoxinas da água não são verificadas imediatamente antes do uso.', ['7.2.7', '7.2.7.1']),
 ('18.6.7.1', 'I', 'Há registros dessa verificação antes do uso?',
  'Há registros da verificação da água antes do uso.', 'Não há registros da verificação da água antes do uso.', ['7.2.7']),
 ('18.6.8', 'I', 'Há medidas corretivas e preventivas estabelecidas e registradas para laudo insatisfatório da água?',
  'Há medidas corretivas e preventivas registradas para laudo insatisfatório da água.', 'Não há medidas corretivas e preventivas registradas para laudo insatisfatório da água.', ['7.2.8']),
 ('18.6.8.1', 'I', 'A efetividade dessas medidas é avaliada por nova análise?',
  'A efetividade das medidas é avaliada por nova análise.', 'A efetividade das medidas não é avaliada por nova análise.', ['7.2.8']),
 ('18.6.8.9', 'I', 'O processo de obtenção da água para estéreis está validado?',
  'O processo de obtenção da água para estéreis está validado.', 'O processo de obtenção da água para estéreis não está validado.', ['7.2.9']),
 # 18.7 Manipulação
 ('18.7.1', 'N', 'São tomadas precauções para minimizar a contaminação em todas as etapas da manipulação?',
  'São tomadas precauções para minimizar a contaminação em todas as etapas.', 'Não são tomadas precauções suficientes para minimizar a contaminação.', ['8.1']),
 ('18.7.2', 'I', 'A manipulação é feita com técnica asséptica?',
  'A manipulação é feita com técnica asséptica.', 'A manipulação não é feita com técnica asséptica.', ['8.2']),
 ('18.7.2.1', 'N', 'A técnica asséptica segue procedimento escrito?',
  'A técnica asséptica segue procedimento escrito.', 'A técnica asséptica não segue procedimento escrito.', ['8.2']),
 ('18.7.3', 'I', 'O processo de manipulação está validado?',
  'O processo de manipulação está validado.', 'O processo de manipulação não está validado.', ['8.2', '10.1.2']),
 ('18.7.3.1', 'I', 'Há registros da validação do processo de manipulação?',
  'Há registros da validação do processo de manipulação.', 'Não há registros da validação do processo de manipulação.', ['10.1.5']),
 ('18.7.4', 'N', 'Há programa de monitoramento ambiental da qualidade microbiológica da sala de manipulação?',
  'Há programa de monitoramento ambiental da sala de manipulação.', 'Não há programa de monitoramento ambiental da sala de manipulação.', ['8.3']),
 ('18.7.4.1', 'N', 'Há registros do monitoramento ambiental?',
  'Há registros do monitoramento ambiental.', 'Não há registros do monitoramento ambiental.', ['8.3']),
 ('18.7.5', 'N', 'É verificado o cumprimento da lavagem de mãos e antebraços dos manipuladores?',
  'É verificado o cumprimento da lavagem de mãos e antebraços.', 'Não é verificado o cumprimento da lavagem de mãos e antebraços.', ['8.4']),
 ('18.7.6', 'N', 'É verificado o cumprimento da limpeza e desinfecção das áreas, instalações, equipamentos e materiais?',
  'É verificado o cumprimento da limpeza e desinfecção das áreas e equipamentos.', 'Não é verificado o cumprimento da limpeza e desinfecção das áreas e equipamentos.', ['8.5']),
 ('18.7.7', 'N', 'Especialidades farmacêuticas, produtos para saúde e recipientes são limpos e desinfetados antes de entrar na área de manipulação?',
  'Os materiais são limpos e desinfetados antes de entrar na área de manipulação.', 'Os materiais não são limpos e desinfetados antes de entrar na área de manipulação.', ['8.6']),
 ('18.7.8', 'N', 'As especialidades farmacêuticas usadas recebem tratamento para assepsia externa e inspeção visual quanto a partículas?',
  'As especialidades farmacêuticas recebem assepsia externa e inspeção visual quanto a partículas.', 'As especialidades farmacêuticas não recebem assepsia externa ou inspeção visual quanto a partículas.', ['8.7']),
 ('18.7.9', 'N', 'A ordem de manipulação registra o lote e o fabricante ou fornecedor de cada especialidade, produto para saúde ou matéria-prima usada?',
  'A ordem de manipulação registra lote e fabricante de cada componente usado.', 'A ordem de manipulação não registra lote e fabricante de cada componente usado.', ['8.8']),
 ('18.7.10', 'N', 'As embalagens primárias estéreis são transportadas de forma a manter a esterilidade até o envase?',
  'As embalagens primárias estéreis são transportadas de forma a manter a esterilidade.', 'O transporte das embalagens primárias estéreis não garante a esterilidade até o envase.', ['8.9']),
 ('18.7.11', 'N', 'Todas as superfícies de trabalho, inclusive o interior da capela de fluxo laminar, são limpas e desinfetadas antes e depois de cada sessão?',
  'As superfícies de trabalho e o interior do fluxo laminar são limpos e desinfetados antes e depois de cada sessão.', 'As superfícies de trabalho ou o interior do fluxo laminar não são limpos e desinfetados antes e depois de cada sessão.', ['8.10']),
 ('18.7.11.1', 'N', 'Há registros dessa limpeza e desinfecção das superfícies?',
  'Há registros da limpeza e desinfecção das superfícies de trabalho.', 'Não há registros da limpeza e desinfecção das superfícies de trabalho.', ['8.10']),
 ('18.7.12', 'N', 'Há registros da limpeza e desinfecção dos equipamentos usados na manipulação?',
  'Há registros da limpeza e desinfecção dos equipamentos da manipulação.', 'Não há registros da limpeza e desinfecção dos equipamentos da manipulação.', ['8.11']),
 ('18.7.13', 'INF', 'Há esterilização final por calor dos produtos manipulados?',
  'Há esterilização final por calor dos produtos manipulados.', 'Não há esterilização final por calor dos produtos manipulados.', ['4.13.5']),
 ('18.7.14', 'INF', 'A esterilização final é feita na sala de limpeza e higienização?',
  'A esterilização final é feita na sala de limpeza e higienização.', 'A esterilização final não é feita na sala de limpeza e higienização.', ['4.13.5']),
 ('18.7.14.1', 'N', 'Quando feita nessa sala, a esterilização segue procedimento e ocorre em horário distinto das demais atividades?',
  'A esterilização na sala de limpeza segue procedimento e ocorre em horário distinto.', 'A esterilização na sala de limpeza não segue procedimento ou não ocorre em horário distinto.', ['4.13.5']),
 ('18.7.15', 'I', 'O envase de preparações esterilizadas por filtração é feito sob fluxo laminar ISO 5, em sala ISO 7?',
  'O envase das preparações esterilizadas por filtração é feito sob fluxo laminar ISO 5, em sala ISO 7.', 'O envase das preparações esterilizadas por filtração não é feito sob fluxo laminar ISO 5 em sala ISO 7.', ['8.12.3']),
 ('18.7.15.1', 'I', 'É feito teste de integridade do filtro esterilizante antes e depois da filtração?',
  'É feito teste de integridade do filtro esterilizante antes e depois da filtração.', 'Não é feito teste de integridade do filtro esterilizante antes e depois da filtração.', ['8.13']),
 ('18.7.15.2', 'I', 'Há registros do teste de integridade do filtro esterilizante?',
  'Há registros do teste de integridade do filtro esterilizante.', 'Não há registros do teste de integridade do filtro esterilizante.', ['8.13']),
 ('18.7.16', 'N', 'Todas as soluções passam por filtração em membrana compatível com o método de esterilização final?',
  'As soluções passam por filtração em membrana compatível com a esterilização final.', 'Nem todas as soluções passam por filtração em membrana compatível com a esterilização final.', ['8.14']),
 ('18.7.16.1', 'N', 'É verificada a integridade da membrana filtrante antes e depois da filtração?',
  'É verificada a integridade da membrana filtrante antes e depois da filtração.', 'Não é verificada a integridade da membrana filtrante antes e depois da filtração.', ['8.14']),
 ('18.7.16.2', 'N', 'Há registros da verificação da membrana filtrante?',
  'Há registros da verificação da membrana filtrante.', 'Não há registros da verificação da membrana filtrante.', ['8.14']),
 ('18.7.17', 'I', 'Todos os processos de esterilização são validados e monitorados conforme procedimento escrito?',
  'Os processos de esterilização são validados e monitorados conforme procedimento escrito.', 'Os processos de esterilização não são validados ou monitorados conforme procedimento escrito.', ['8.15']),
 ('18.7.17.1', 'I', 'Os resultados do monitoramento da esterilização são registrados e arquivados?',
  'Os resultados do monitoramento da esterilização são registrados e arquivados.', 'Os resultados do monitoramento da esterilização não são registrados.', ['8.15']),
 ('18.7.18', 'N', 'Há procedimento claro para diferenciar preparações esterilizadas das não esterilizadas?',
  'Há procedimento para diferenciar preparações esterilizadas das não esterilizadas.', 'Não há procedimento para diferenciar preparações esterilizadas das não esterilizadas.', ['8.15.1']),
 ('18.7.19', 'R', 'Nos injetáveis, os produtos intermediários são monitorados quanto a endotoxinas?',
  'Os produtos intermediários injetáveis são monitorados quanto a endotoxinas.', 'Recomenda-se monitorar os produtos intermediários injetáveis quanto a endotoxinas.', ['8.17']),
 ('18.7.20', 'N', 'Está estabelecido, por produto, o tempo máximo entre o início da manipulação e a esterilização ou filtração esterilizante?',
  'Está estabelecido o tempo máximo entre o início da manipulação e a esterilização.', 'Não está estabelecido o tempo máximo entre o início da manipulação e a esterilização.', ['8.18']),
 ('18.7.21', 'N', 'Todas as unidades de produtos estéreis passam por revisão e inspeção?',
  'Todas as unidades de produtos estéreis passam por revisão e inspeção.', 'Nem todas as unidades de produtos estéreis passam por revisão e inspeção.', ['8.20']),
 ('18.7.22', 'R', 'É feito teste de hermeticidade dos produtos estéreis?',
  'É feito teste de hermeticidade dos produtos estéreis.', 'Recomenda-se realizar teste de hermeticidade dos produtos estéreis.', ['8.21']),
 ('18.7.23', 'N', 'Há sistema de identificação que separe com segurança as preparações antes e depois da revisão?',
  'Há sistema de identificação que separa as preparações antes e depois da revisão.', 'Não há sistema de identificação que separe as preparações antes e depois da revisão.', ['8.22']),
 ('18.7.24', 'N', 'O rótulo traz paciente, leito e registro, composição, volume, velocidade de infusão, via, data e hora, número de controle, conservação e transporte, farmacêutico com CRF e quem preparou?',
  'A rotulagem dos produtos estéreis traz as informações exigidas.', 'A rotulagem dos produtos estéreis não traz todas as informações exigidas.', ['8.23']),
 # 18.8 Controle de qualidade
 ('18.8.1', 'N', 'As matérias-primas passam por ensaios farmacopeicos completos: identificação, teor, impurezas e biocarga?',
  'As matérias-primas passam pelos ensaios farmacopeicos completos, incluindo a biocarga.', 'As matérias-primas não passam pelos ensaios farmacopeicos completos, incluindo a biocarga.', ['9.1']),
 ('18.8.1.1', 'INF', 'Os ensaios de teor, impurezas e biocarga são feitos por laboratório terceirizado?',
  'Os ensaios de teor, impurezas e biocarga são terceirizados.', 'Os ensaios de teor, impurezas e biocarga são feitos pela própria farmácia.', ['9.2']),
 ('18.8.2', 'I', 'O produto pronto passa por inspeção visual de 100% das unidades, conferência do rótulo, teste de esterilidade e de endotoxinas (exceto oftálmicos)?',
  'O produto pronto passa pela inspeção visual, conferência do rótulo e testes de esterilidade e de endotoxinas.', 'O produto pronto não passa por todos os controles exigidos (inspeção visual, rótulo, esterilidade e endotoxinas).', ['9.3', '9.5']),
 ('18.8.2.1', 'N', 'As amostras do teste de esterilidade são retiradas de forma representativa a cada ciclo de esterilização?',
  'As amostras do teste de esterilidade são representativas de cada ciclo.', 'As amostras do teste de esterilidade não são representativas de cada ciclo.', ['9.3.1']),
 ('18.8.2.2', 'I', 'Todas as análises são registradas?',
  'Todas as análises são registradas.', 'Nem todas as análises são registradas.', ['9.4']),
 # 18.9 Garantia da qualidade
 ('18.9.1', 'I', 'Os equipamentos e as salas classificadas são qualificados ou certificados?',
  'Os equipamentos e as salas classificadas são qualificados ou certificados.', 'Os equipamentos ou as salas classificadas não são qualificados ou certificados.', ['10.1.1']),
 ('18.9.2', 'I', 'Os ciclos de esterilização e despirogenização são validados?',
  'Os ciclos de esterilização e despirogenização são validados.', 'Os ciclos de esterilização e despirogenização não são validados.', ['10.1.1']),
 ('18.9.3', 'I', 'O sistema de obtenção de água para estéreis está validado?',
  'O sistema de obtenção de água para estéreis está validado.', 'O sistema de obtenção de água para estéreis não está validado.', ['10.1.1']),
 ('18.9.4', 'I', 'O procedimento de preparação de estéreis está validado para garantir a obtenção do medicamento estéril?',
  'O procedimento de preparação de estéreis está validado.', 'O procedimento de preparação de estéreis não está validado.', ['10.1.2']),
 ('18.9.4.1', 'N', 'A validação segue protocolo escrito, com procedimento simulado da técnica?',
  'A validação segue protocolo escrito, com procedimento simulado.', 'A validação não segue protocolo escrito com procedimento simulado.', ['10.1.2.1']),
 ('18.9.4.2', 'I', 'A validação abrange a metodologia, cada manipulador e as condições da área e dos equipamentos?',
  'A validação abrange a metodologia, os manipuladores e as condições da área e dos equipamentos.', 'A validação não abrange a metodologia, os manipuladores ou as condições da área e dos equipamentos.', ['10.1.2.2']),
 ('18.9.5', 'N', 'Há revalidação periódica, no mínimo anual?',
  'Há revalidação periódica, no mínimo anual.', 'Não há revalidação anual.', ['10.1.3']),
 ('18.9.6', 'N', 'O procedimento é revalidado sempre que há alteração nas condições validadas?',
  'O procedimento é revalidado quando há alteração nas condições validadas.', 'O procedimento não é revalidado quando há alteração nas condições validadas.', ['10.1.4']),
 ('18.9.7', 'I', 'As validações e revalidações são documentadas e arquivadas por dois anos?',
  'As validações e revalidações são documentadas e arquivadas.', 'As validações e revalidações não são documentadas e arquivadas.', ['10.1.5', '10.2.1']),
 # 18.10 Citostáticos
 ('18.10.1', 'N', 'Os citostáticos são armazenados em local exclusivo, em condições que preservem identidade e integridade?',
  'Os citostáticos são armazenados em local exclusivo e adequado.', 'Os citostáticos não são armazenados em local exclusivo e adequado.', ['11.1']),
 ('18.10.2', 'I', 'Há sala exclusiva para manipulação e fracionamento de citostáticos?',
  'Há sala exclusiva para manipulação e fracionamento de citostáticos.', 'Não há sala exclusiva para manipulação e fracionamento de citostáticos.', ['11.2']),
 ('18.10.3', 'N', 'A sala de citostáticos tem pressão negativa em relação ao ambiente adjacente?',
  'A sala de citostáticos tem pressão negativa em relação ao adjacente.', 'A sala de citostáticos não tem pressão negativa em relação ao adjacente.', ['11.3']),
 ('18.10.4', 'I', 'Todas as operações são feitas em Cabine de Segurança Biológica Classe II B2?',
  'As operações com citostáticos são feitas em Cabine de Segurança Biológica Classe II B2.', 'As operações com citostáticos não são feitas em Cabine de Segurança Biológica Classe II B2.', ['11.4']),
 ('18.10.5', 'N', 'A cabine é validada semestralmente e após deslocamento ou reparo?',
  'A cabine de segurança biológica é validada semestralmente e após deslocamento ou reparo.', 'A cabine de segurança biológica não é validada semestralmente ou após deslocamento ou reparo.', ['11.5']),
 ('18.10.5.1', 'N', 'Há registros das validações da cabine?',
  'Há registros das validações da cabine.', 'Não há registros das validações da cabine.', ['11.5']),
 ('18.10.6', 'N', 'Qualquer interrupção da cabine paralisa imediatamente a manipulação de citostáticos?',
  'A interrupção da cabine paralisa imediatamente a manipulação de citostáticos.', 'A manipulação de citostáticos não é paralisada quando a cabine é interrompida.', ['11.6']),
 ('18.10.7', 'I', 'Na manipulação são usados dois pares de luvas estéreis de látex, de punho longo e sem talco, e avental longo ou macacão de baixa permeabilidade?',
  'São usados dois pares de luvas estéreis e avental ou macacão de baixa permeabilidade.', 'Não são usados os dois pares de luvas estéreis e o avental ou macacão de baixa permeabilidade exigidos.', ['11.7.1']),
 ('18.10.8', 'N', 'As luvas são trocadas a cada hora ou quando comprometidas?',
  'As luvas são trocadas a cada hora ou quando comprometidas.', 'As luvas não são trocadas a cada hora ou quando comprometidas.', ['11.7.1']),
 ('18.10.9', 'N', 'A paramentação reutilizável é guardada separada, em ambiente fechado, até a lavagem?',
  'A paramentação reutilizável é guardada separada até a lavagem.', 'A paramentação reutilizável não é guardada separada até a lavagem.', ['11.7.2']),
 ('18.10.9.1', 'N', 'A lavagem desse vestuário é exclusiva?',
  'A lavagem do vestuário de citostáticos é exclusiva.', 'A lavagem do vestuário de citostáticos não é exclusiva.', ['11.7.2']),
 ('18.10.10', 'N', 'O produto final passa por inspeção visual quanto a perfurações, vazamentos, corpos estranhos e precipitados?',
  'O produto final passa por inspeção visual.', 'O produto final não passa por inspeção visual.', ['11.7.3']),
 ('18.10.11', 'N', 'O transporte é feito em recipientes isotérmicos exclusivos, protegidos de intempéries e da luz solar direta?',
  'O transporte de citostáticos é feito em recipientes isotérmicos exclusivos e protegidos.', 'O transporte de citostáticos não é feito em recipientes isotérmicos exclusivos e protegidos.', ['11.8.1']),
 ('18.10.12', 'N', 'O responsável pelo transporte recebeu treinamento de biossegurança para acidentes e emergências?',
  'O responsável pelo transporte recebeu treinamento de biossegurança.', 'O responsável pelo transporte não recebeu treinamento de biossegurança.', ['11.8.2']),
 ('18.10.13', 'N', 'A contaminação acidental no transporte é notificada ao responsável pela manipulação?',
  'A contaminação acidental no transporte é notificada ao responsável pela manipulação.', 'A contaminação acidental no transporte não é notificada ao responsável pela manipulação.', ['11.8.3']),
 ('18.10.13.1', 'I', 'São adotadas descontaminação e limpeza conforme os protocolos estabelecidos?',
  'São adotadas descontaminação e limpeza conforme os protocolos.', 'Não são adotadas descontaminação e limpeza conforme os protocolos.', ['11.8.3']),
 ('18.10.14', 'R', 'A farmácia tem Programa de Biossegurança implantado?',
  'A farmácia tem Programa de Biossegurança implantado.', 'Recomenda-se implantar Programa de Biossegurança.', ['11.9.1']),
 ('18.10.15', 'N', 'Há kit de derramamento identificado e disponível em todas as áreas de manipulação, armazenamento e transporte?',
  'Há kit de derramamento identificado nas áreas de manipulação, armazenamento e transporte.', 'Não há kit de derramamento identificado em todas as áreas de manipulação, armazenamento e transporte.', ['11.9.2']),
 ('18.10.16', 'N', 'O kit contém luvas, avental de baixa permeabilidade, compressas absorventes, proteção respiratória e ocular e sabão?',
  'O kit de derramamento contém os itens exigidos.', 'O kit de derramamento não contém todos os itens exigidos.', ['11.9.2.1']),
 ('18.10.17', 'N', 'O kit traz a descrição do procedimento, formulário de registro do acidente e recipiente identificado para os resíduos?',
  'O kit traz o procedimento, o formulário de registro e o recipiente para resíduos.', 'O kit não traz o procedimento, o formulário de registro ou o recipiente para resíduos.', ['11.9.2.1']),
 ('18.10.18', 'N', 'Há normas e rotinas escritas, revisadas anualmente, para o uso da cabine e dos EPI?',
  'Há normas escritas e revisadas anualmente para o uso da cabine e dos EPI.', 'Não há normas escritas e revisadas anualmente para o uso da cabine e dos EPI.', ['11.9.3']),
 ('18.10.19', 'N', 'Todos os acidentes são registrados em formulário específico?',
  'Os acidentes são registrados em formulário específico.', 'Os acidentes não são registrados em formulário específico.', ['11.9.4']),
 ('18.10.20', 'N', 'Há procedimentos específicos para acidentes com pessoal, na cabine e no ambiente?',
  'Há procedimentos específicos para acidentes com pessoal, na cabine e no ambiente.', 'Não há procedimentos específicos para acidentes com pessoal, na cabine e no ambiente.', ['11.9.4']),
]
